# Generated by Django 6.0 on 2025-12-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('made_by', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=50)),
                ('reason_for_payment', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('currency', models.CharField(default='PHP', max_length=10)),
            ],
        ),
    ]
